### ISSUE TITLE
Eures - strftime error in analyzePage

### ISSUE THREAD

**Issue by yoannsculo** [yoannsculo/JobCatcher#18]
Error in unstable (57e3d23) with jobcatcher -a

```
==================================
Eures
==================================
Download http://ec.europa.eu/eures/eures-searchengine/servlet/./ShowJvServlet?lg=FR&pesId=62&uniqueJvId=004GKRV&nnImport=false 
Download http://ec.europa.eu/eures/eures-searchengine/servlet/./ShowJvServlet?lg=FR&pesId=62&uniqueJvId=004GPYD&nnImport=false 
Download http://ec.europa.eu/eures/eures-searchengine/servlet/./ShowJvServlet?lg=FR&pesId=62&uniqueJvId=007PFFX&nnImport=false 
Download http://ec.europa.eu/eures/eures-searchengine/servlet/./ShowJvServlet?lg=FR&pesId=62&uniqueJvId=007WGKK&nnImport=false 
Download http://ec.europa.eu/eures/eures-searchengine/servlet/./ShowJvServlet?lg=FR&pesId=62&uniqueJvId=008RSZH&nnImport=false 
Download http://ec.europa.eu/eures/eures-searchengine/servlet/./ShowJvServlet?lg=FR&pesId=62&uniqueJvId=008TBSP&nnImport=false 
Download http://ec.europa.eu/eures/eures-searchengine/servlet/./ShowJvServlet?lg=FR&pesId=62&uniqueJvId=009XWRX&nnImport=false 
Download http://ec.europa.eu/eures/eures-searchengine/servlet/./ShowJvServlet?lg=FR&pesId=62&uniqueJvId=009XWRZ&nnImport=false 
Download http://ec.europa.eu/eures/eures-searchengine/servlet/./ShowJvServlet?lg=FR&pesId=62&uniqueJvId=009XWSG&nnImport=false 
Download http://ec.europa.eu/eures/eures-searchengine/servlet/./ShowJvServlet?lg=FR&pesId=62&uniqueJvId=009XWYB&nnImport=false 
Traceback (most recent call last):
  File "./jobcatcher.py", line 638, in <module>
    executeall(configs)
  File "./jobcatcher.py", line 544, in executeall
    pagesinsert(conf)
  File "./jobcatcher.py", line 574, in pagesinsert
    fd.analyzesPages()
  File "./jobcatcher.py", line 79, in analyzesPages
    plugin.analyzePage(content.url, content.page)
  File "/home/yoann/dev/apec/jobboards/Eures.py", line 81, in analyzePage
    "%d/%m/%Y").strftime('%s')
TypeError: must be string, not None
```

**Comment by yscialom** [comment]
Could not reproduce. But trying, i find a new one. Please see issue #19.
My guess is that jobboard/Eures.py:80

``` python
    self._extractItem("Date de publication", html)
```

can sometime return None. May be can you fix that by testing the result value of _extractItem.

Edit: can't make the github "Fenced code blocks" working.
