### ISSUE TITLE
Robust error processing on offer fetching

### ISSUE THREAD

**Issue by yoannsculo** [yoannsculo/JobCatcher#76]
Jobcatch should not crash when a parsing error occurs.
Errors should be catched and formatted for bug tracking. Error messages should Ideally have a context (feed, url, offer, etc.) to ease developer's work.

**Comment by yoannsculo** [comment]
For instance, when I use --p2psync I can fetch old offers that cause a crash in jobcatcher.

```
Insert pages to jobboard
Analyse error page http://candidat.pole-emploi.fr/candidat/rechercheoffres/detail/010FSKQ(Not block content found)
Traceback (most recent call last):
  File "jobcatcher.py", line 295, in <module>
    executeall(configs, selecteduser)
  File "jobcatcher.py", line 41, in executeall
    insertpages(conf, selecteduser)
  File "jobcatcher.py", line 111, in insertpages
    insertpage(conf, jobboardname)
  File "jobcatcher.py", line 96, in insertpage
    page.load()
  File "/home/yoann/dev/apec/jc/page.py", line 59, in load
    webpage = utilities.openPage(filename)
  File "/home/yoann/dev/apec/utilities.py", line 129, in openPage
    PAGEVERSION
Exception: Mauvaise version pour ./www/dl/PoleEmploi/pages/984a0165d7d31c73ee1c6cebf86b071e/e6ad4b5f70d40a5ff65d0b9526b7db33.page=e6ad4b5f70d40a5ff65d0b9526b7db33 attendu 1.0
```
